{
 "title": "AdGuard",
 "tags": [
  "dns",
  "adguard",
  "network"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Exporter",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(max(adguard_exporter_up) == 1) or on() (max(adguard_exporter_up) * NaN)",
     "legendFormat": "UP"
    },
    {
     "expr": "(1 - min(adguard_exporter_up) == 1) or on() (min(adguard_exporter_up) * NaN)",
     "legendFormat": "DOWN"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_exporter_scrape_duration_seconds",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Inbound Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "q/s" } },
   "targets": [
    {
     "expr": "rate(adguard_dns_queries_total[$__rate_interval])",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Protection",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "(max(adguard_protection_enabled) == 1) or on() (max(adguard_protection_enabled) * NaN)",
     "legendFormat": "ON"
    },
    {
     "expr": "(1 - max(adguard_protection_enabled) == 1) or on() (max(adguard_protection_enabled) * NaN)",
     "legendFormat": "OFF"
    }
   ]
  },
  {
   "title": "Block Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(adguard_blocked_filtering_total / adguard_dns_queries_total) * 100",
     "legendFormat": "Block Rate"
    }
   ]
  },
  {
   "title": "Upstream Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "q/s" } },
   "targets": [
    {
     "expr": "sum by (norm_upstream) (label_replace(rate(adguard_query_upstream_total[$__rate_interval]), \"norm_upstream\", \"$2\", \"upstream\", \"(tcp://|udp://)?(.+)\"))",
     "legendFormat": "{{norm_upstream}}"
    }
   ]
  },
  {
   "title": "Upstream Queries Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * histogram_quantile(0.95, sum by (le, norm_upstream) (label_replace(rate(adguard_upstream_latency_seconds_bucket{}[$__rate_interval]), \"norm_upstream\", \"$2\", \"upstream\", \"(tcp://|udp://)?(.+)\")))",
     "legendFormat": "{{norm_upstream}}"
    }
   ]
  },
  {
   "title": "Query Types",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(\n  increase(adguard_query_type_total[$__rate_interval])\n  or (\n    label_replace(vector(0.01), \"type\", \"A\", \"\", \"\")\n    or label_replace(vector(0.01), \"type\", \"AAAA\", \"\", \"\")\n    or label_replace(vector(0.01), \"type\", \"CAA\", \"\", \"\")\n    or label_replace(vector(0.01), \"type\", \"CNAME\", \"\", \"\")\n    or label_replace(vector(0.01), \"type\", \"HTTPS\", \"\", \"\")\n    or label_replace(vector(0.01), \"type\", \"MX\", \"\", \"\")\n    or label_replace(vector(0.01), \"type\", \"NS\", \"\", \"\")\n    or label_replace(vector(0.01), \"type\", \"PTR\", \"\", \"\")\n    or label_replace(vector(0.01), \"type\", \"SOA\", \"\", \"\")\n    or label_replace(vector(0.01), \"type\", \"SRV\", \"\", \"\")\n    or label_replace(vector(0.01), \"type\", \"TXT\", \"\", \"\")\n  )\n) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Upstream Latency Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(increase(adguard_upstream_latency_seconds_bucket{le=\"0.008\"}[$__rate_interval])) / clamp_min(sum(increase(adguard_upstream_latency_seconds_count[$__rate_interval])), 1)",
     "legendFormat": "≤ 8 ms"
    },
    {
     "expr": "100 * (sum(increase(adguard_upstream_latency_seconds_bucket{le=\"0.064\"}[$__rate_interval])) - sum(increase(adguard_upstream_latency_seconds_bucket{le=\"0.008\"}[$__rate_interval]))) / clamp_min(sum(increase(adguard_upstream_latency_seconds_count[$__rate_interval])), 1)",
     "legendFormat": "≤ 64 ms"
    },
    {
     "expr": "100 * (sum(increase(adguard_upstream_latency_seconds_bucket{le=\"0.256\"}[$__rate_interval])) - sum(increase(adguard_upstream_latency_seconds_bucket{le=\"0.064\"}[$__rate_interval]))) / clamp_min(sum(increase(adguard_upstream_latency_seconds_count[$__rate_interval])), 1)",
     "legendFormat": "≤ 256 ms"
    },
    {
     "expr": "100 * (sum(increase(adguard_upstream_latency_seconds_bucket{le=\"0.512\"}[$__rate_interval])) - sum(increase(adguard_upstream_latency_seconds_bucket{le=\"0.256\"}[$__rate_interval]))) / clamp_min(sum(increase(adguard_upstream_latency_seconds_count[$__rate_interval])), 1)",
     "legendFormat": "≤ 512 ms"
    },
    {
     "expr": "100 * (sum(increase(adguard_upstream_latency_seconds_count[$__rate_interval])) - sum(increase(adguard_upstream_latency_seconds_bucket{le=\"0.512\"}[$__rate_interval]))) / clamp_min(sum(increase(adguard_upstream_latency_seconds_count[$__rate_interval])), 1)",
     "legendFormat": "> 512 ms"
    }
   ]
  }
 ]
}