filters:
  - name: "AdGuard DNS filter"
    url: "https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt"

  - name: "AdAway Default Blocklist"
    url: "https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt"

  - name: "HaGeZi's Pro++ Blocklist"
    url: "https://adguardteam.github.io/HostlistsRegistry/assets/filter_51.txt"

  - name: "OISD Blocklist Big"
    url: "https://adguardteam.github.io/HostlistsRegistry/assets/filter_27.txt"

  - name: "HaGeZi's Gambling Blocklist"
    url: "https://adguardteam.github.io/HostlistsRegistry/assets/filter_47.txt"

  - name: "HaGeZi's Badware Hoster Blocklist"
    url: "https://adguardteam.github.io/HostlistsRegistry/assets/filter_55.txt"

  - name: "uBlock filters - Badware risks"
    url: "https://adguardteam.github.io/HostlistsRegistry/assets/filter_50.txt"

  - name: "Malicious URL Blocklist (URLHaus)"
    url: "https://adguardteam.github.io/HostlistsRegistry/assets/filter_11.txt"

  - name: "Stalkerware Indicators List"
    url: "https://adguardteam.github.io/HostlistsRegistry/assets/filter_31.txt"

  - name: "Phishing Army"
    url: "https://adguardteam.github.io/HostlistsRegistry/assets/filter_18.txt"
