{
 "title": "Unbound",
 "tags": [
  "dns",
  "network",
  "unbound"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Exporter",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(max(unbound_up) == 1) or on() (max(unbound_up) * NaN)",
     "legendFormat": "UP"
    },
    {
     "expr": "((1 - max(unbound_up) == 1)) or on() (max(unbound_up) * NaN)",
     "legendFormat": "OFF"
    }
   ]
  },
  {
   "title": "Recursive RTT ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(unbound_response_time_seconds_bucket[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "title": "Msg Cch / 64M",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cache) (unbound_memory_caches_bytes{cache=\"message\"}) / 67108864 * 100",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "RRSet Cch / 128M",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cache) (unbound_memory_caches_bytes{cache=\"rrset\"}) / 134217728 * 100",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Cch Hit Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(unbound_cache_hits_total[$__rate_interval])) / (sum(rate(unbound_cache_hits_total[$__rate_interval])) + sum(rate(unbound_cache_misses_total[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cch Prefetches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(unbound_prefetches_total[$__rate_interval]))",
     "legendFormat": "Ops"
    }
   ]
  },
  {
   "title": "Inbound Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(unbound_queries_total[$__rate_interval]))",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "title": "Cache Hit / Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(unbound_answer_rcodes_total[$__rate_interval])) - sum(rate(unbound_recursive_replies_total[$__rate_interval]))",
     "legendFormat": "Hits"
    },
    {
     "expr": "-1 * sum(rate(unbound_recursive_replies_total[$__rate_interval]))",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Cache Miss Packets Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(unbound_query_udpout_total[$__rate_interval]))\r\n/\r\nsum(rate(unbound_cache_misses_total[$__rate_interval]))",
     "legendFormat": "UDP"
    },
    {
     "expr": "sum(rate(unbound_query_tcpout_total[$__rate_interval]))\r\n/\r\nsum(rate(unbound_cache_misses_total[$__rate_interval]))",
     "legendFormat": "TCP"
    }
   ]
  },
  {
   "title": "Cache Miss Queries TTR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(unbound_response_time_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    }
   ]
  }
 ]
}