namespace: monitoring
revision: 9

ingressHost: grafana
ingressHelmParam: 'grafana\.ini.server.root_url'

source:
  repoURL: https://grafana.github.io/helm-charts
  chart: grafana
  targetRevision: 8.5.1
  helm:
    values:
      admin:
        existingSecret: grafana-admin
        userKey: admin-user
        passwordKey: admin-password

      service:
        type: ClusterIP

      persistence:
        enabled: true
        size: 1Gi

      plugins:
        - grafana-polystat-panel

      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          labelValue: "1"
          searchNamespace: monitoring
          folderAnnotation: grafana_folder
          provider:
            foldersFromFilesStructure: true
            allowUiUpdates: false
            updateIntervalSeconds: 30
        alerts:
          enabled: true
          label: grafana_alert
          labelValue: "1"
          searchNamespace: monitoring
          provider:
            foldersFromFilesStructure: true
            allowUiUpdates: false
            updateIntervalSeconds: 30

      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Prometheus
              uid: prometheus
              type: prometheus
              access: proxy
              url: http://prometheus-server.monitoring.svc:80
              isDefault: true

      envValueFrom:
        SLACK_BOT_TOKEN:
          secretKeyRef:
            name: grafana-slack
            key: token

      "grafana.ini":
        server:
          serve_from_sub_path: false
        dashboards:
          default_home_dashboard_path: /tmp/dashboards/homelab.json