{
 "title": "DNS Overview",
 "tags": [
  "dns",
  "network",
  "adguard",
  "unbound"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "AdGuard Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(max(adguard_running) == 1) or on() (max(adguard_running) * NaN)",
     "legendFormat": "UP"
    },
    {
     "expr": "(1 - min(adguard_running) == 1) or on() (min(adguard_running) * NaN)",
     "legendFormat": "DOWN"
    }
   ]
  },
  {
   "title": "Protection",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "(max(adguard_protection_enabled) == 1) or on() (max(adguard_protection_enabled) * NaN)",
     "legendFormat": "ON"
    },
    {
     "expr": "(1 - max(adguard_protection_enabled) == 1) or on() (max(adguard_protection_enabled) * NaN)",
     "legendFormat": "OFF"
    }
   ]
  },
  {
   "title": "Protection Inactive",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_protection_disabled_duration_seconds",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Exporter",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "(max(adguard_exporter_up) == 1) or on() (max(adguard_exporter_up) * NaN)",
     "legendFormat": "UP"
    },
    {
     "expr": "(1 - min(adguard_exporter_up) == 1) or on() (min(adguard_exporter_up) * NaN)",
     "legendFormat": "DOWN"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_exporter_scrape_duration_seconds",
     "legendFormat": "Duration"
    }
   ]
  },
  { "title": "Unbound Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Service",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "(max(unbound_up) == 1) or on() (max(unbound_up) * NaN)",
     "legendFormat": "UP"
    },
    {
     "expr": "((1 - max(unbound_up) == 1)) or on() (max(unbound_up) * NaN)",
     "legendFormat": "OFF"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "unbound_time_up_seconds_total", "legendFormat": "UP" }
   ]
  },
  {
   "title": "Msg Cache / 64M",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cache) (unbound_memory_caches_bytes{cache=\"message\"}) / 67108864 * 100",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Msg Cache",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "unbound_msg_cache_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RRSet Cache / 128M",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cache) (unbound_memory_caches_bytes{cache=\"rrset\"}) / 134217728 * 100",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "RRSet Cache",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "unbound_rrset_cache_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queries",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(adguard_dns_queries_total[$__range]))",
       "legendFormat": "queries"
      }
     ]
    },
    {
     "title": "Block Rate",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(adguard_blocked_filtering_total / adguard_dns_queries_total) * 100",
       "legendFormat": "Block Rate"
      }
     ]
    },
    {
     "title": "Query Types",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 3 },
     "targets": [
      {
       "expr": "sum(increase(adguard_query_type_total[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Top 10 Queried Domains",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 3 },
     "targets": [
      {
       "expr": "topk(\r\n  10,\r\n  sum by (domain) (\r\n    increase(\r\n      adguard_top_queried_domain_total[$__rate_interval]\r\n    )\r\n  )\r\n)",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Cache Hits",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(unbound_cache_hits_total[$__rate_interval])) /\r\n(\r\n  sum(rate(unbound_cache_hits_total[$__rate_interval])) +\r\n  sum(rate(unbound_cache_misses_total[$__rate_interval]))\r\n)",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Cache Prefetch",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(unbound_prefetches_total[$__rate_interval]))",
       "legendFormat": "Ops"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Queries Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "q/s" } },
   "targets": [
    {
     "expr": "rate(adguard_dns_queries_total[$__rate_interval])",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Total Queries TTR, p95",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.95, \r\n    sum(\r\n        rate(adguard_query_elapsed_ms_bucket[$__rate_interval])\r\n    ) by (le)\r\n)",
     "legendFormat": "le"
    }
   ]
  },
  {
   "title": "Upstream Queries Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "q/s" } },
   "targets": [
    {
     "expr": "sum by (upstream) (\r\n    rate(adguard_query_upstream_total[$__rate_interval])\r\n)",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  {
   "title": "Upstream Queries TTR, p95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * histogram_quantile(\r\n    0.95, \r\n    sum by (le, upstream) (\r\n        rate(adguard_upstream_latency_seconds_bucket{}[$__rate_interval])\r\n    )\r\n)",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  {
   "title": "Recursion Packets Sent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(unbound_query_udpout_total[$__rate_interval]))\r\n/\r\nsum(rate(unbound_cache_misses_total[$__rate_interval]))",
     "legendFormat": "UDP"
    },
    {
     "expr": "sum(rate(unbound_query_tcpout_total[$__rate_interval]))\r\n/\r\nsum(rate(unbound_cache_misses_total[$__rate_interval]))",
     "legendFormat": "TCP"
    }
   ]
  },
  {
   "title": "Recursion Queries TTR, p95",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.95, \r\n    sum(\r\n        rate(unbound_response_time_seconds_bucket[$__rate_interval])\r\n    ) by (le)\r\n)",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Upstream Cache Hit / Miss",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(\r\n    increase(unbound_cache_hits_total[$__rate_interval])\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "-1 * sum(\r\n    increase(unbound_cache_misses_total[$__rate_interval])\r\n)",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Upstream Queries TTR, %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(\r\n    increase(adguard_upstream_latency_seconds_bucket{le=\"0.008\"}[$__rate_interval])\r\n) \r\n/ \r\nclamp_min(\r\n    sum(\r\n        increase(adguard_upstream_latency_seconds_count[$__rate_interval])\r\n    ), \r\n    1\r\n)",
     "legendFormat": "≤ 8 ms"
    },
    {
     "expr": "100 * (\r\n    sum(\r\n        increase(adguard_upstream_latency_seconds_bucket{le=\"0.064\"}[$__rate_interval])\r\n    ) \r\n    - \r\n    sum(\r\n        increase(adguard_upstream_latency_seconds_bucket{le=\"0.008\"}[$__rate_interval])\r\n    )\r\n) \r\n/ \r\nclamp_min(\r\n    sum(\r\n        increase(adguard_upstream_latency_seconds_count[$__rate_interval])\r\n    ), \r\n    1\r\n)",
     "legendFormat": "≤ 64 ms"
    },
    {
     "expr": "100 * (\r\n    sum(\r\n        increase(adguard_upstream_latency_seconds_bucket{le=\"0.256\"}[$__rate_interval])\r\n    ) \r\n    - \r\n    sum(\r\n        increase(adguard_upstream_latency_seconds_bucket{le=\"0.064\"}[$__rate_interval])\r\n    )\r\n) \r\n/ \r\nclamp_min(\r\n    sum(\r\n        increase(adguard_upstream_latency_seconds_count[$__rate_interval])\r\n    ), \r\n    1\r\n)",
     "legendFormat": "≤ 256 ms"
    },
    {
     "expr": "100 * (\r\n    sum(\r\n        increase(adguard_upstream_latency_seconds_bucket{le=\"0.512\"}[$__rate_interval])\r\n    ) \r\n    - \r\n    sum(\r\n        increase(adguard_upstream_latency_seconds_bucket{le=\"0.256\"}[$__rate_interval])\r\n    )\r\n) \r\n/ \r\nclamp_min(\r\n    sum(\r\n        increase(adguard_upstream_latency_seconds_count[$__rate_interval])\r\n    ), \r\n    1\r\n)",
     "legendFormat": "≤ 512 ms"
    },
    {
     "expr": "100 * (\r\n    sum(\r\n        increase(adguard_upstream_latency_seconds_count[$__rate_interval])\r\n    ) \r\n    - \r\n    sum(\r\n        increase(adguard_upstream_latency_seconds_bucket{le=\"0.512\"}[$__rate_interval])\r\n    )\r\n) \r\n/ \r\nclamp_min(\r\n    sum(\r\n        increase(adguard_upstream_latency_seconds_count[$__rate_interval])\r\n    ), \r\n    1\r\n)",
     "legendFormat": "> 512 ms"
    }
   ]
  }
 ]
}