apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dns

resources:
  - deployment.yaml
  - service.yaml
  - service-exporter.yaml
  - pvc-cache.yaml
configMapGenerator:
  - name: unbound-config
    files:
      - unbound.conf
generatorOptions:
  disableNameSuffixHash: false
