apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unbound-cache
  namespace: dns
  labels:
    app.kubernetes.io/name: unbound
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 256Mi
