apiVersion: v1
kind: Service
metadata:
  name: unbound-exporter
  namespace: dns
  labels:
    app.kubernetes.io/name: unbound-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9167"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: unbound
  ports:
    - name: metrics
      port: 9167
      targetPort: metrics
      protocol: TCP
