apiVersion: v1
kind: Service
metadata:
  name: argocd-metrics
  namespace: argocd
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8082"
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server-metrics
  namespace: argocd
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8083"
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-repo-server
  namespace: argocd
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8084"
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-applicationset-controller
  namespace: argocd
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
